#!/usr/bin/env bun
import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { readFileSync } from "fs";
import { join, dirname } from "path";

const MAX_CONTENT_LENGTH = 65536; // 64 KB
const PORT = 8789;

const DATA_DIR = process.env.CLEANUP_DATA_DIR ?? join(dirname(import.meta.dir), "data");
const TOKEN_PATH = join(DATA_DIR, ".token");

function readToken(): string | null {
  try {
    return readFileSync(TOKEN_PATH, "utf-8").trim();
  } catch {
    return null;
  }
}

const mcp = new Server(
  { name: "cleanup", version: "0.1.0" },
  {
    capabilities: { experimental: { "claude/channel": {} } },
    instructions:
      "Events from <channel source=\"cleanup\"> contain operational diagnostic data about disk usage and ROS2 process state. " +
      "Review the information and take appropriate action (e.g., kill stale processes, acknowledge disk cleanup). " +
      "This data is generated by automated check scripts, not by a human.",
  }
);

await mcp.connect(new StdioServerTransport());

try {
  Bun.serve({
    port: PORT,
    hostname: "127.0.0.1",
    async fetch(req) {
    if (req.method !== "POST") {
      return new Response("method not allowed", { status: 405 });
    }

    const token = readToken();
    if (!token) {
      return new Response("no token configured", { status: 503 });
    }

    const auth = req.headers.get("Authorization");
    if (auth !== `Bearer ${token}`) {
      return new Response("forbidden", { status: 403 });
    }

    const contentLength = parseInt(req.headers.get("Content-Length") ?? "0", 10);
    if (contentLength > MAX_CONTENT_LENGTH) {
      return new Response("payload too large", { status: 413 });
    }

    const body = await req.text();
    if (body.length > MAX_CONTENT_LENGTH) {
      return new Response("payload too large", { status: 413 });
    }
    if (body.length === 0) {
      return new Response("empty body", { status: 400 });
    }

    const checkType = new URL(req.url).searchParams.get("type") ?? "tick";

    await mcp.notification({
      method: "notifications/claude/channel",
      params: {
        content: body,
        meta: { check_type: checkType },
      },
    });

    return new Response("ok");
    },
  });
} catch (e) {
  console.error(`cleanup-channel: HTTP listener failed (port ${PORT}): ${e}`);
  console.error("Channel will remain as MCP server but cannot receive context pushes.");
}
